# Numpy

In [1]:
import numpy as np

In [2]:
a=np.arange(6)
print(a)

[0 1 2 3 4 5]


In [3]:
a.shape

(6,)

making it 2D

In [4]:
a2=a[np.newaxis,:]
print(a2)

[[0 1 2 3 4 5]]


In [5]:
a2.shape

(1, 6)

In [6]:
# or we can write it as
a21=a[:,np.newaxis]
print(a21)
a21.shape

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


(6, 1)

In [7]:
# making it 3d
a3=a2[np.newaxis,:]
print(a3)
a3.shape

[[[0 1 2 3 4 5]]]


(1, 1, 6)

## Creating Arrays with Numpy

In [8]:
# 1D array
a=np.array([1,2,3])
print(a)
print(a.shape)
# 2D array
b=np.array([[1,2,3],[4,5,6]])
print(b)
b.shape

[1 2 3]
(3,)
[[1 2 3]
 [4 5 6]]


(2, 3)

In [9]:
zeros=np.zeros((3,4)) #(rows,columns)
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
ones=np.ones((3,4)) #(rows,columns)
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [11]:
full=np.full((3,4),5) #(rows,columns)
print(full)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [12]:
# identity matrix
eye=np.eye(4)
print(eye)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [13]:
# check the data type of the array
eye.dtype

dtype('float64')

In [14]:
# type of a
type(a)

numpy.ndarray

In [15]:
# dimensions of array
print(a.ndim)
print(b.ndim)
print(eye.ndim)

1
2
2


In [16]:
# size of array or no. of elements in array
eye.size

16

In [17]:
print(a)
print(b)
print(b-a)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[[0 0 0]
 [3 3 3]]


In [18]:
# or we can use
print(np.subtract(b,a))

[[0 0 0]
 [3 3 3]]


In [19]:
# same for addition
print(b+a)
print(np.add(b,a))

[[2 4 6]
 [5 7 9]]
[[2 4 6]
 [5 7 9]]


In [20]:
# square of array b
print(b**2)

[[ 1  4  9]
 [16 25 36]]


## Numpy p2

In [21]:
#making empty array
empty=np.empty((5,4))
print(empty)
print('------------------')
print(empty[0])

[[6.23042070e-307 4.67296746e-307 1.69121096e-306 2.33647015e-307]
 [8.34441742e-308 8.90104239e-307 1.33511290e-306 1.42417221e-306]
 [1.37961641e-306 1.24611538e-306 8.01097889e-307 1.78020169e-306]
 [7.56601165e-307 1.02359984e-306 1.33510679e-306 2.22522597e-306]
 [2.22523140e-306 1.24611945e-306 1.42410974e-306 8.45610230e-307]]
------------------
[6.23042070e-307 4.67296746e-307 1.69121096e-306 2.33647015e-307]


In [22]:
# even no. upto to 23
c=np.arange(0,23,2)
print(c)

[ 0  2  4  6  8 10 12 14 16 18 20 22]


In [26]:
# dividing 0 to 10 in 5 equal parts
lin=np.linspace(0, 10, num=9)
lin

array([ 0.  ,  1.25,  2.5 ,  3.75,  5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [28]:
# also specify the data type
lin=np.linspace(0, 10, num=15, dtype=int)
lin

array([ 0,  0,  1,  2,  2,  3,  4,  5,  5,  6,  7,  7,  8,  9, 10])

In [29]:
# sorting the array
a=np.array([[1,4,2],[3,2,6]])
a=np.sort(a)
print(a)

[[1 2 4]
 [2 3 6]]


In [30]:
#concatenating the array
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.concatenate((a,b))
print(c)

[1 2 3 4 5 6]


In [36]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6]])
c=np.concatenate((a,b))
print(c)
c.ndim

[[1 2]
 [3 4]
 [5 6]]


2

In [37]:
a=np.array([[1,2],[3,4]])
b=np.array([[5],[6]])
c=np.concatenate((a,b),axis=1)
print(c)
c.ndim

[[1 2 5]
 [3 4 6]]


2

In [61]:
# create a 3d array
a=np.array([[[1],[3]],[[1],[2]], [[3],[4]]])
print(a)

[[[1]
  [3]]

 [[1]
  [2]]

 [[3]
  [4]]]


In [49]:
a.ndim

3

In [44]:
a.shape

(3, 2, 1)

In [40]:
a.size

8

In [64]:
# reshaping the array
a=a.reshape(3,2,1)
print(a)

[[[1]
  [3]]

 [[1]
  [2]]

 [[3]
  [4]]]


In [59]:
a.shape

(2, 3)

In [65]:
b=np.arange(0,12,2)
print(b)

[ 0  2  4  6  8 10]


In [69]:
print(b[-5:-1])

[2 4 6 8]


In [82]:
a=np.array([1,2,3,4]).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [85]:
b = a + np.array([5,6])
print(b)
print('------------------')
c=np.vstack((a, np.array([5,6])))
print(c)



[[ 6  8]
 [ 8 10]]
------------------
[[1 2]
 [3 4]
 [5 6]]
